In [2]:
# iris 데이터 불러오기
import pandas as pd
import numpy as np

iris = pd.read_csv('./iris.csv')

In [3]:
iris

sepal length  sepal width  petal length  petal width     target
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [27]:
iris.target.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [4]:
x = iris.iloc[:, 0:4]
y = iris.iloc[:, -1]

In [7]:
# 전처리
from sklearn.preprocessing import LabelEncoder, RobustScaler

label = LabelEncoder()
y = label.fit_transform(y)

sc = RobustScaler()
x = sc.fit_transform(x)

In [11]:
# train, test set 나누기
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=99, stratify=y)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
print(cross_val_score(RandomForestClassifier(), x_train, y_train, cv=3).mean())

0.9583333333333334


In [28]:
model = RandomForestClassifier()
model.fit(x_train, y_train)
predict = model.predict_proba(x_test)
output=pd.DataFrame({'setosa':predict[:,0], 'versicolor':predict[:,1], 'virginica':predict[:,2]})
#output.to_csv('123.csv', index=False)

In [29]:
predict

array([[0.  , 1.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.  , 0.96, 0.04],
       [0.  , 0.  , 1.  ],
       [0.  , 0.98, 0.02],
       [0.99, 0.01, 0.  ],
       [0.  , 0.  , 1.  ],
       [0.99, 0.  , 0.01],
       [0.  , 1.  , 0.  ],
       [0.99, 0.  , 0.01],
       [0.  , 0.09, 0.91],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.01, 0.91, 0.08],
       [0.99, 0.01, 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 0.17, 0.83],
       [0.  , 0.  , 1.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 0.01, 0.99],
       [0.99, 0.01, 0.  ],
       [0.  , 0.26, 0.74],
       [0.  , 0.  , 1.  ]])

In [30]:
output

setosa  versicolor  virginica
0     0.00        1.00       0.00
1     0.99        0.01       0.00
2     0.00        0.00       1.00
3     1.00        0.00       0.00
4     1.00        0.00       0.00
5     1.00        0.00       0.00
6     1.00        0.00       0.00
7     0.00        1.00       0.00
8     0.00        0.99       0.01
9     0.00        0.96       0.04
10    0.00        0.00       1.00
11    0.00        0.98       0.02
12    0.99        0.01       0.00
13    0.00        0.00       1.00
14    0.99        0.00       0.01
15    0.00        1.00       0.00
16    0.99        0.00       0.01
17    0.00        0.09       0.91
18    0.00        1.00       0.00
19    0.00        1.00       0.00
20    0.01        0.91       0.08
21    0.99        0.01       0.00
22    0.00        0.00       1.00
23    0.00        0.17       0.83
24    0.00        0.00       1.00
25    0.00        0.00       1.00
26    0.00        0.01       0.99
27    0.99        0.01       0.00
28    0.00        0.26       0.74
29    0.00        0.00       1.00

In [21]:
# 모델 평가
import sklearn.metrics as met
print(met.confusion_matrix(y_test, model.predict(x_test)))
print(met.accuracy_score(y_test, model.predict(x_test)))

[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
0.9666666666666667
